# Robert's Cross Practice

Essentially I didn't master implementing this concept in class, so now I want to figure it out on my own terms.

## Let's make sure the working directory is correct:

In [1]:
pwd

'C:\\Users\\chris\\Desktop\\misc\\hobbyStuff\\Programs\\Robberts cross\\main'

In [2]:
ls

 Volume in drive C is Windows
 Volume Serial Number is F8FD-8A6F

 Directory of C:\Users\chris\Desktop\misc\hobbyStuff\Programs\Robberts cross\main

05/20/2021  11:06 AM    <DIR>          .
05/20/2021  11:06 AM    <DIR>          ..
05/19/2021  01:19 PM    <DIR>          .ipynb_checkpoints
05/20/2021  11:06 AM            11,303 Roberts Cross Practice.ipynb
05/19/2021  01:12 PM             1,817 square_basic.png
05/19/2021  02:20 PM             1,921 square_basic_blue.png
               3 File(s)         15,041 bytes
               3 Dir(s)  856,865,832,960 bytes free


## Import statements

In [1]:
import numpy as np

In [2]:
import PIL            #import pillow to process images
from PIL import Image # is this one even nessisary? posibbly remove
import math

## Experemental Additions

These are set up for my eventual goal of making the process a definition and testing it with loops to see if the algorithm works for difrent images.

In [3]:
images = ["square_basic.png", "square_basic_blue.png"] # I hope to eventualy use this to make the bellow a 
                                                        #function to call in a loop for this array

In [4]:
threshold = .9 #how much of a difrence there must be for the algorythm to consider it


In [5]:
#experimental to create a range of thresholds to be able to check which is better
thresholds = range(0, 100, 10) 

print(thresholds)

range(0, 100, 10)


Essentially here is the algorythm plan so far:
    -import and succesfully store an image as an array of pixels
        -properly understand how to interpret that array and its indices
    -figure out exacly what type of loop needed/ # of itterations
    -inside the loop:
        -check if you get either of the 4 edge patterns
    
    ****figure out how to put these possitives and negatives together into something usefull!**************

## Getting Pillow to work


In [5]:
with Image.open(images[1]) as im:    #is there a better way to do this?
    im.show() #to make sure the image selected is the correct image

In [12]:
im = im.convert('L') #makes it greyscale
im = im.resize((round(im.size[0]*0.125), round(im.size[1]*0.125))) #make it smaller

In [13]:
height = im.height
width = im.width
i_shape = im.size

In [14]:
#testors
print("height:\t", height)
print("width:\t", width)
print("shape:\t", i_shape)

height:	 15
width:	 14
shape:	 (14, 15)


In [15]:
orig_image = np.asarray(im)

In [21]:
edges_only = np.zeros((height, width))

## testing if the conversion worked

In [22]:
#print(orig_image) 
print("does the shape match?\t", "\nim.size ==",  height," " , width, "\norig_image.shape ==", orig_image.shape)

test = Image.fromarray(orig_image)
test.show() #image should be in greyscale and much smaller now

does the shape match?	 
im.size == 15   14 
orig_image.shape == (15, 14)


## now the loop to cycle through the array

In [23]:
print(orig_image)
print(orig_image.shape)

print(edges_only)
print(edges_only.shape)

[[255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 237 225 228 228 228 228 228 228 228 227 227 254 255]
 [255 228 247 252 252 252 252 252 252 252 252 227 250 255]
 [255 230 250 255 255 255 255 255 255 255 255 230 250 255]
 [255 230 250 255 255 255 255 255 255 255 255 230 250 255]
 [255 230 250 255 255 255 255 255 255 255 255 230 250 255]
 [255 230 250 255 255 255 255 255 255 255 255 230 250 255]
 [255 230 250 255 255 255 255 255 255 255 255 230 250 255]
 [255 230 251 255 255 255 255 255 255 255 255 230 250 255]
 [255 228 243 249 249 249 249 249 249 249 248 225 250 255]
 [255 241 228 230 230 230 230 230 230 230 230 231 254 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [255 255 255 255 255 255 255 255 255 255 255 255 255 255]]
(15, 14)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0

In [24]:
print(width - 1)
print(height - 1)

13
14


In [25]:
count = 0
#this is causing an index out of bounds error -- figure out why
for i in range(height - 1):
    for j in range(width -1):
        #print("i, j: ", i, " ", j)
        
        patch = []
        patch.append(orig_image[i, j]) #grabs the image patch (4 pixels)   #find a better way to do this
        patch.append(orig_image[i+1, j])
        patch.append(orig_image[i, j+1])
        patch.append(orig_image[i+1, j+1])
        
        
        ##patch = orig_image[i:i+1, j: j+1] #grabs the image patch (4 pixels)
       # print(patch.shape)
       # print("patch\n", patch, "\n\n")              #why is it comming out in such a weird format? which index is which?
        
        
        ratio = np.sqrt((patch[0] - patch[3])**2 + (patch[1] - patch[2])**2)
        
        #print(ratio)
        
        #if ratio != 0.0: count+=1
        if ratio >= threshold: count+=1
        print(count)
        edges_only[i,j] = ratio


0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
42
42
42
42
42
42
42
43
44
45
46
47
48
48
48
48
48
48
48
48
49
50
51
52
53
54
54
54
54
54
54
54
54
55
56
57
58
59
60
60
60
60
60
60
60
60
61
62
63
64
65
66
66
66
66
66
66
66
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
108
108
108
108
108
108
108
108
108
108
108
108
108


<ipython-input-25-16d4aae463e9>:19: RuntimeWarning: overflow encountered in ubyte_scalars
  ratio = np.sqrt((patch[0] - patch[3])**2 + (patch[1] - patch[2])**2)


In [26]:
print(edges_only)

test = Image.fromarray(edges_only)
test.show()

[[  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.        ]
 [  0.           0.           0.           0.           0.
    0.           0.           0.           0.           0.
    0.           0.           0.           0.        ]
 [ 18.         239.88330496 227.60711764 230.58620947 230.58620947
  230.58620947 230.58620947 230.58620947 230.58620947 230.7054399
  229.71286425 228.00219297 255.           0.        ]
 [ 32.44996148 246.018292   229.78685776 233.23807579 233.23807579
  233.23807579 233.23807579 233.23807579 233.23807579 233.34309503
   25.         326.69557695 357.80721066   0.        ]
 [ 36.79673899 334.48019373 354.99295768 253.01778594 253.01778594
  253.01778594 253.01778594 253.01778594 253.01778594 253.01778594
   35.60898763 331.63986491 354.96760416   0.        ]
 [ 35.35533906 333.75440072 354.96760416   0.           0.
    0.           0.          