# Robert's Cross Practice

Essentially I didn't master implementing this concept in class, so now I want to figure it out on my own terms.

## Let's make sure the working directory is correct:

In [13]:
pwd

'C:\\Users\\chris\\Desktop\\misc\\hobbyStuff\\Programs\\Robberts cross\\main'

In [14]:
ls

 Volume in drive C is Windows
 Volume Serial Number is F8FD-8A6F

 Directory of C:\Users\chris\Desktop\misc\hobbyStuff\Programs\Robberts cross\main

05/19/2021  02:24 PM    <DIR>          .
05/19/2021  02:24 PM    <DIR>          ..
05/19/2021  01:19 PM    <DIR>          .ipynb_checkpoints
05/19/2021  02:24 PM             8,346 Roberts Cross Practice.ipynb
05/19/2021  01:12 PM             1,817 square_basic.png
05/19/2021  02:20 PM             1,921 square_basic_blue.png
               3 File(s)         12,084 bytes
               3 Dir(s)  857,520,050,176 bytes free


## Import statements

In [15]:
import numpy as np

In [4]:
import PIL            #import pillow to process images
from PIL import Image # is this one even nessisary? posibbly remove

## Experemental Additions

These are set up for my eventual goal of making the process a definition and testing it with loops to see if the algorithm works for difrent images.

In [18]:
images = ["square_basic.png", "square_basic_blue.png"] # I hope to eventualy use this to make the bellow a 
                                                        #function to call in a loop for this array

In [25]:
threshold = .9 #how much of a difrence there must be for the algorythm to consider it


In [29]:
#experimental to create a range of thresholds to be able to check which is better
thresholds = range(0, 100, 10) 

print(thresholds)

range(0, 100, 10)


Essentially here is the algorythm plan so far:
    -import and succesfully store an image as an array of pixels
        -properly understand how to interpret that array and its indices
    -figure out exacly what type of loop needed/ # of itterations
    -inside the loop:
        -check if you get either of the 4 edge patterns
    
    ****figure out how to put these possitives and negatives together into something usefull!**************

## Getting Pillow to work


In [7]:
with Image.open("square_basic.png") as im:
    im.show() #to make sure the image selected is the correct image

In [8]:
height = im.height
width = im.width
i_shape = im.size

In [9]:
#testors
print("height:\t", height)
print("width:\t", width)
print("shape:\t", i_shape)

height:	 411
width:	 511
shape:	 (511, 411)


In [10]:
#make an np array to hold the image
orig_image = np.empty(shape = i_shape)

In [11]:
#what pillow recomends as general format of convert
#Image.convert(mode=None, matrix=None, dither=None, palette=0, colors=256)
im.convert(matrix=orig_image, colors=2) #ensures this image is in greyscale

In [12]:
print(orig_image) #proves that this part of the code didn't really work -- need find a way to fix it

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
